services:
  bot:
    container_name: bot
    image: ${REGISTRY_URL}/${GITHUB_REPOSITORY}:${TAG:-main}
    depends_on:
      - redis
      - export-html
    volumes:
      - ./logs:/opt/logs
      - ./config:/opt/config
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"

  export-html:
    container_name: export-html
    image: bedrockio/export-html:latest
    expose:
      - "2305"
    restart: always

  redis:
    container_name: redis
    image: 'redis:latest'
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis-data:/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"


  watchtower:
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: -i 60
    volumes:
      - /home/ubuntu/.docker:/config
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis-data: